#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef ATOMICXCORE_SWIFT_H
#define ATOMICXCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AtomicXCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// AI real-time transcription related interfaces, managing real-time speech-to-text transcription and translation features.
/// <code>AITranscriberStore</code> AI real-time transcription management class for handling speech-to-text transcription and translation business.
/// <code>AITranscriberStore</code> provides a complete set of AI real-time transcription management APIs, including starting, updating, and stopping real-time transcription.
/// Through this class, you can implement real-time speech-to-text transcription with multi-language translation support during audio/video calls or live streaming.
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>Real-time Transcription</em>：Supports real-time speech-to-text transcription during audio/video sessions
///   </li>
///   <li>
///     <em>Multi-language Source</em>：Supports 20 source languages including Chinese, English, Japanese, Korean, etc.
///   </li>
///   <li>
///     <em>Real-time Translation</em>：Supports translating transcribed text into 15 target languages in real-time
///   </li>
///   <li>
///     <em>State Management</em>：Provides real-time message list state for UI display
///   </li>
/// </ul>
/// <blockquote>
/// Important: Use the <code>create(roomID:)</code> factory method to create an <code>AITranscriberStore</code> instance for a specific room. Configure the source language and translation languages before starting transcription.
///
/// </blockquote>
/// <blockquote>
/// Note: Transcription state updates are delivered through the <code>state</code> publisher. Subscribe to it to receive real-time transcription messages.
///
/// </blockquote>
/// <h3>Usage Example</h3>
/// \code
/// // Create instance for a specific room
/// let store = AITranscriberStore.create(roomID: "your_room_id")
///
/// // Subscribe to state changes
/// store.state.subscribe { state in
///     for message in state.realtimeMessageList {
///         print("Speaker: \(message.speakerUserName)")
///         print("Source text: \(message.sourceText)")
///     }
/// }
///
/// // Configure transcription
/// var config = TranscriberConfig()
/// config.sourceLanguage = .chineseEnglish
/// config.translationLanguages = [.english, .japanese]
///
/// // Start transcription
/// store.startRealtimeTranscriber(config: config) { error in
///     if let error = error {
///         print("Start failed: \(error)")
///     }
/// }
///
/// \endcode<h2>Topics</h2>
/// <h3>Getting Instance</h3>
/// <ul>
///   <li>
///     <code>create(roomID:) - Create an instance for a specific room</code>
///   </li>
/// </ul>
/// <h3>Observing State and Events</h3>
/// <ul>
///   <li>
///     <code>state - Transcriber state data</code>
///   </li>
/// </ul>
/// <h3>Transcription Control</h3>
/// <ul>
///   <li>
///     <code>startTranscription(myLanguage:config:completion:) - Start transcription</code>
///   </li>
///   <li>
///     <code>updateTranscription(myLanguage:config:completion:) - Update transcription configuration</code>
///   </li>
///   <li>
///     <code>stopTranscription(completion:) - Stop transcription</code>
///   </li>
/// </ul>
/// <h3>Interpretation Control</h3>
/// <ul>
///   <li>
///     <code>startInterpretation(myLanguage:config:completion:) - Start interpretation</code>
///   </li>
///   <li>
///     <code>updateInterpretation(myLanguage:config:completion:) - Update interpretation configuration</code>
///   </li>
///   <li>
///     <code>stopInterpretation(completion:) - Stop interpretation</code>
///   </li>
///   <li>
///     <code>setInterpretationVolume(_:completion:) - Set interpretation volume</code>
///   </li>
/// </ul>
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>SourceLanguage</code>
///   </li>
///   <li>
///     <code>TranslationLanguage</code>
///   </li>
///   <li>
///     <code>InterpretationVoice</code>
///   </li>
///   <li>
///     <code>TranscriberMessage</code>
///   </li>
///   <li>
///     <code>TranscriptionConfig</code>
///   </li>
///   <li>
///     <code>InterpretationConfig</code>
///   </li>
///   <li>
///     <code>TranscriberState</code>
///   </li>
///   <li>
///     <code>AITranscriberStoreEvent</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11AtomicXCore18AITranscriberStore")
@interface AITranscriberStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

/// Core call view component responsible for video rendering and interactive display of the call interface. Supports multi-layout switching (single-person float/multi-person grid/picture-in-picture), call waiting animations, and personalized configuration of volume, network status, and user avatars.
/// <code>CallCoreView</code> Core view component for displaying call screens.
/// <code>CallCoreView</code> is the main container for the call interface, providing the following core capabilities:
/// <ul>
///   <li>
///     <em>Multi-Layout Switching</em>: Supports switching between single-person float, multi-person grid, and picture-in-picture layouts.
///   </li>
///   <li>
///     <em>Call Waiting Interaction</em>: Supports custom waiting animations before call connection.
///   </li>
///   <li>
///     <em>Status Visualization</em>: Supports custom icons for different volume levels and network quality states.
///   </li>
///   <li>
///     <em>User Personalization</em>: Supports setting participant avatars through User ID mapping.
///   </li>
/// </ul>
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>Multi-Layout Switching</em>：Supports switching between single-person float, multi-person grid, and picture-in-picture layouts.
///   </li>
///   <li>
///     <em>Call Waiting Interaction</em>：Supports custom waiting animations before call connection.
///   </li>
///   <li>
///     <em>Status Visualization</em>：Supports custom icons for different volume levels and network quality states.
///   </li>
///   <li>
///     <em>User Personalization</em>：Supports setting participant avatars through User ID mapping.
///   </li>
/// </ul>
/// <blockquote>
/// Note: This view component must be used together with <code>CallStore</code> to properly display call screens and receive call state updates.
///
/// </blockquote>
/// <h3>Method Overview</h3>
/// | Feature | Method | Description |
/// |—––|——|———–|
/// | Multi-Layout Switching | <code>setLayoutTemplate(_:)</code> | Switch call interface layout (single-person float/multi-person grid/PiP) |
/// | Waiting Animation | <code>setWaitingAnimation(path:)</code> | Set the loading animation during call waiting state |
/// | Volume Icons | <code>setVolumeLevelIcons(icons:)</code> | Customize icons for each volume level |
/// | Network Icons | <code>setNetworkQualityIcons(icons:)</code> | Customize icons for each network quality level |
/// | User Avatars | <code>setParticipantAvatars(avatars:)</code> | Set participant avatar images |
/// <h3>Usage Example</h3>
/// \code
/// import AtomicXCore
///
/// // Create call view
/// let callCoreView = CallCoreView(frame: view.bounds)
/// view.addSubview(callCoreView)
///
/// // Set layout mode
/// callCoreView.setLayoutTemplate(.grid)
///
/// // Set waiting animation
/// callCoreView.setWaitingAnimation(path: "waiting_animation.json")
///
/// // Set volume icons
/// callCoreView.setVolumeLevelIcons(icons: [
///     .mute: "volume_mute",
///     .low: "volume_low",
///     .medium: "volume_medium",
///     .high: "volume_high",
///     .peak: "volume_peak"
/// ])
///
/// // Set network quality icons
/// callCoreView.setNetworkQualityIcons(icons: [
///     .unknown: "network_unknown",
///     .excellent: "network_excellent",
///     .good: "network_good",
///     .poor: "network_poor",
///     .bad: "network_bad",
///     .veryBad: "network_very_bad",
///     .down: "network_down"
/// ])
///
/// // Set participant avatars
/// callCoreView.setParticipantAvatars(avatars: [
///     "user_123": "avatar_user_123",
///     "user_456": "avatar_user_456"
/// ])
///
/// \endcode<h2>Topics</h2>
/// <h3>Static Properties</h3>
/// <ul>
///   <li>
///     <code>defaultAvatarImage - Default placeholder avatar.</code>
///   </li>
///   <li>
///     <code>waitingAnimationImage - Call waiting animation.</code>
///   </li>
///   <li>
///     <code>volumeImages - Volume status icon collection.</code>
///   </li>
///   <li>
///     <code>networkQualityImages - Network signal icon collection.</code>
///   </li>
///   <li>
///     <code>participantAvatars - Participant avatar collection.</code>
///   </li>
/// </ul>
/// <h3>Configuration Methods</h3>
/// <ul>
///   <li>
///     <code>setLayoutTemplate(_:) - Multi-layout switching.</code>
///   </li>
///   <li>
///     <code>setWaitingAnimation(path:) - Configure waiting animation.</code>
///   </li>
///   <li>
///     <code>setVolumeLevelIcons(icons:) - Configure volume icons.</code>
///   </li>
///   <li>
///     <code>setNetworkQualityIcons(icons:) - Configure network icons.</code>
///   </li>
///   <li>
///     <code>setParticipantAvatars(avatars:) - Configure participant avatars.</code>
///   </li>
/// </ul>
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>CallLayoutTemplate</code>
///   </li>
///   <li>
///     <code>VolumeLevel</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11AtomicXCore12CallCoreView")
@interface CallCoreView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


@interface CallCoreView (SWIFT_EXTENSION(AtomicXCore))
- (void)didMoveToWindow;
@end


SWIFT_CLASS("_TtC11AtomicXCore19CallParticipantView")
@interface CallParticipantView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11AtomicXCore11CallPipView")
@interface CallPipView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToWindow;
@end


/// Audio/video call management APIs for initiating, answering, rejecting, hanging up calls, group call management, and call history management.
/// <code>CallStore</code> Manages all audio/video call related operations.
/// Including initiating, answering, rejecting, hanging up, group call management, and call history management.
/// Audio/video call functionality is implemented through <code>CallStore</code> for real-time audio/video interaction between users. <code>CallStore</code> provides a comprehensive set of APIs to manage the entire call lifecycle.
/// When integrating <code>CallStore</code>, please be aware of the following runtime characteristics:
/// <ul>
///   <li>
///     <em>Error Handling</em>: When actively calling an API (e.g., <code>calls</code>), if the call itself fails due to parameter validation or state conflicts, you will typically be notified via an asynchronously thrown error event or a returned error code. Network or remote-side anomalies are also delivered through <code>onCallEnded</code> with the error reason attached.
///   </li>
///   <li>
///     <em>Threading Model & Cleanup</em>: All state updates (<code>CallState</code>) and event callbacks (<code>CallEvent</code> / <code>CallEventListener</code>) are typically <em>guaranteed to fire on the main thread</em>, so they can be used directly to refresh the UI. Under the global singleton pattern, be sure to unregister listeners when components are destroyed (e.g., <code>deinit</code> / <code>onDestroy</code>) to avoid memory leaks.
///   </li>
/// </ul>
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>Create Audio/Video Calls</em>：Support initiating audio or video calls to one or multiple users, with configurable timeout, custom data, and other parameters.
///   </li>
///   <li>
///     <em>Answer/Reject Audio/Video Calls</em>：When receiving an incoming call invitation, you can choose to answer or reject.
///   </li>
///   <li>
///     <em>Hang Up Audio/Video Calls</em>：End the current ongoing audio/video call.
///   </li>
///   <li>
///     <em>Group Call Management</em>：Support joining existing group calls or inviting other users to join during a call.
///   </li>
///   <li>
///     <em>Call History Management</em>：Query recent call records (with pagination support), delete specified call records.
///   </li>
///   <li>
///     <em>Event-Driven Architecture</em>：Provides event listeners for call started, call received, call ended, etc.
///   </li>
///   <li>
///     <em>State Subscription</em>：Real-time subscription to current call state, including participant list, volume information, network quality, etc.
///   </li>
/// </ul>
/// <blockquote>
/// Important: Ensure the SDK is initialized before accessing the <code>shared</code> singleton. Do not instantiate it directly, as doing so will prevent you from receiving call state updates.
///
/// </blockquote>
/// <blockquote>
/// Note: Call state updates are delivered through the <code>state</code> publisher. Subscribe to it to receive real-time updates of call data.
///
/// </blockquote>
/// <h3>Call Operations Overview</h3>
/// The following table shows the main call operations.
/// | Feature | Method | Description |
/// |—––|——|———–|
/// | Create Call | <code>calls</code> | Create an audio or video call to specified users |
/// | Answer Call | <code>accept</code> | Answer an incoming call |
/// | Reject Call | <code>reject</code> | Reject an incoming call |
/// | Hang Up Call | <code>hangup</code> | Hang up the current call |
/// | Join Call | <code>join</code> | Actively join a group call |
/// | Invite Users | <code>invite</code> | Invite other users to join the current call |
/// | Experimental API | <code>callExperimentalAPI</code> | Call experimental API |
/// <h3>Call History Management</h3>
/// | Feature | Method | Description |
/// |—––|——|———–|
/// | Query Records | <code>queryRecentCalls</code> | Query recent call records (with pagination support) |
/// | Delete Records | <code>deleteRecentCalls</code> | Delete specified call records |
/// <h3>Usage Example</h3>
/// \code
/// import AtomicXCore
///
/// // Create a video call
/// CallStore.shared.calls(participantIds: ["mike"], mediaType: .video, params: nil) { code, message in
/// }
///
/// \endcode<blockquote>
/// Warning: Please ensure proper handling of UI state after the call ends to avoid UI anomalies.
///
/// </blockquote>
/// <h2>Topics</h2>
/// <h3>Get Instance</h3>
/// <ul>
///   <li>
///     <code>shared - Get the CallStore singleton instance.</code>
///   </li>
/// </ul>
/// <h3>Observe State and Events</h3>
/// <ul>
///   <li>
///     <code>state - Reactive state containing active call, participant list, volume information, and network quality.</code>
///   </li>
///   <li>
///     <code>callEventPublisher - Call event publisher.</code>
///   </li>
/// </ul>
/// <h3>Call Operations</h3>
/// <ul>
///   <li>
///     <code>calls - Create a call.</code>
///   </li>
///   <li>
///     <code>accept - Answer a call.</code>
///   </li>
///   <li>
///     <code>reject - Reject a call.</code>
///   </li>
///   <li>
///     <code>hangup - Hang up a call.</code>
///   </li>
///   <li>
///     <code>join - Join a group call.</code>
///   </li>
///   <li>
///     <code>invite - Invite users to join a call.</code>
///   </li>
/// </ul>
/// <h3>Call History</h3>
/// <ul>
///   <li>
///     <code>queryRecentCalls - Query recent call records.</code>
///   </li>
///   <li>
///     <code>deleteRecentCalls - Delete call records.</code>
///   </li>
/// </ul>
/// <h3>Experimental API</h3>
/// <ul>
///   <li>
///     <code>callExperimentalAPI - Call experimental API.</code>
///   </li>
/// </ul>
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>CallMediaType</code>
///   </li>
///   <li>
///     <code>CallEndReason</code>
///   </li>
///   <li>
///     <code>CallDirection</code>
///   </li>
///   <li>
///     <code>CallParticipantStatus</code>
///   </li>
///   <li>
///     <code>CallParams</code>
///   </li>
///   <li>
///     <code>CloudRecordPolicy</code>
///   </li>
///   <li>
///     <code>CallParticipantInfo</code>
///   </li>
///   <li>
///     <code>CallInfo</code>
///   </li>
///   <li>
///     <code>CallState</code>
///   </li>
///   <li>
///     <code>CallEvent</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11AtomicXCore9CallStore")
@interface CallStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11AtomicXCore12ContactStore")
@interface ContactStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore22ConversationGroupStore")
@interface ConversationGroupStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore21ConversationListStore")
@interface ConversationListStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore16GroupMemberStore")
@interface GroupMemberStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore10GroupStore")
@interface GroupStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Live core view component, providing view container for live streaming push and playback, supporting multi-person co-guest, PK and other features.
/// <code>LiveCoreView</code> Live core view component, providing view container for live streaming push and playback.
/// <code>LiveCoreView</code> provides view container for live streaming push and playback, supporting multi-person co-guest, PK and other features.
/// Through this component, video rendering and interaction in live rooms can be implemented.
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>Video Rendering</em>：Provides view container for live streaming push and playback.
///   </li>
///   <li>
///     <em>Co-guest Support</em>：Supports multi-person co-guest feature.
///   </li>
///   <li>
///     <em>PK Support</em>：Supports anchor PK feature.
///   </li>
///   <li>
///     <em>Preview Outside Room</em>：Supports previewing live stream before entering the room.
///   </li>
/// </ul>
/// <blockquote>
/// Important: Before using, you need to call <code>setLiveID(_:)</code> to set the live room ID first.
///
/// </blockquote>
SWIFT_CLASS("_TtC11AtomicXCore12LiveCoreView")
@interface LiveCoreView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end




@interface LiveCoreView (SWIFT_EXTENSION(AtomicXCore))
- (void)didMoveToWindow;
@end









/// Login related interfaces, managing user login, logout, user information settings and other operations.
/// <code>LoginStore</code> Login management class for handling user login, logout and user information management business logic.
/// <code>LoginStore</code> provides a complete set of login management APIs, including user login, logout, and personal information settings.
/// Through this class, you can manage user login status and user profiles.
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>User Login</em>：Supports login using SDK application ID, user ID and user signature.
///   </li>
///   <li>
///     <em>User Logout</em>：Supports user logout operation.
///   </li>
///   <li>
///     <em>Personal Information Settings</em>：Supports setting user nickname, avatar, gender and other personal information.
///   </li>
/// </ul>
/// <blockquote>
/// Important: Use <code>shared</code> singleton object to access the <code>LoginStore</code> instance.
///
/// </blockquote>
/// <blockquote>
/// Note: Login status updates are delivered through <code>state</code> publisher. Subscribe to it to receive real-time updates about login status.
///
/// </blockquote>
/// <h3>Login Operations Overview</h3>
/// | Operation | Method | Description |
/// |———|——|———–|
/// | Login | <code>login(sdkAppID:userID:userSig:completion:)</code> | Login using SDK application ID user ID and user signature |
/// | Logout | <code>logout(completion:)</code> | User logout |
/// | Set Info | <code>setSelfInfo(userProfile:completion:)</code> | Set user personal information |
/// | Push Config | <code>setCertificateID(apnsCertificateID:voipCertificateID:)</code> | Set offline push certificate IDs |
/// <h2>Topics</h2>
/// <h3>Getting Instance</h3>
/// <ul>
///   <li>
///     <code>shared - Singleton object.</code>
///   </li>
/// </ul>
/// <h3>Observing State</h3>
/// <ul>
///   <li>
///     <code>state - Login state.</code>
///   </li>
/// </ul>
/// <h3>Events Handling</h3>
/// <ul>
///   <li>
///     <code>loginEventPublisher - Login event publisher</code>
///   </li>
/// </ul>
/// <h3>Login Operations</h3>
/// <ul>
///   <li>
///     <code>login(sdkAppID:userID:userSig:completion:) - Login.</code>
///   </li>
///   <li>
///     <code>logout(completion:) - Logout.</code>
///   </li>
///   <li>
///     <code>setSelfInfo(userProfile:completion:) - Set personal information.</code>
///   </li>
/// </ul>
/// <h3>Push Configuration</h3>
/// <ul>
///   <li>
///     <code>setCertificateID(apnsCertificateID:voipCertificateID:) - Set offline push certificate IDs.</code>
///   </li>
/// </ul>
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>LoginState</code>
///   </li>
///   <li>
///     <code>UserProfile</code>
///   </li>
///   <li>
///     <code>LoginStatus</code>
///   </li>
///   <li>
///     <code>Gender</code>
///   </li>
///   <li>
///     <code>AllowType</code>
///   </li>
///   <li>
///     <code>LoginEvent</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11AtomicXCore10LoginStore")
@interface LoginStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore16MessageListStore")
@interface MessageListStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Room participant video view for displaying participant video streams.
/// <code>RoomParticipantView</code> View component for displaying room participant video streams.
/// <code>RoomParticipantView</code> is a view component specifically designed for rendering room participant video streams.
/// It supports both camera and screen sharing video stream types, and provides fill mode settings, active state control and other features.
/// <h3>Key Features</h3>
/// <ul>
///   <li>
///     <em>Video Stream Rendering</em>：Supports rendering camera video streams and screen sharing video streams.
///   </li>
///   <li>
///     <em>Fill Mode</em>：Supports FILL and FIT video fill modes.
///   </li>
///   <li>
///     <em>Active State</em>：Supports setting the active state of the view to control video rendering.
///   </li>
///   <li>
///     <em>Gesture Interaction</em>：Supports click and other gesture interactions.
///   </li>
/// </ul>
/// <blockquote>
/// Note: Before use, you need to initialize the video stream type and participant info through <code>init(streamType:participant:)</code> method.
///
/// </blockquote>
/// <h2>Topics</h2>
/// <h3>Creating Instance</h3>
/// <ul>
///   <li>
///     <code>init(streamType:participant:) - Create view instance.</code>
///   </li>
/// </ul>
/// <h3>Video Stream Control</h3>
/// <ul>
///   <li>
///     <code>updateStreamType(streamType:) - Update video stream type.</code>
///   </li>
///   <li>
///     <code>updateParticipant(participant:) - Update participant info.</code>
///   </li>
/// </ul>
/// <h3>View Settings</h3>
/// <ul>
///   <li>
///     <code>setFillMode(fillMode:) - Set fill mode.</code>
///   </li>
///   <li>
///     <code>setActive(isActive:) - Set active state.</code>
///   </li>
/// </ul>
/// <h3>Interaction</h3>
/// <ul>
///   <li>
///     <code>setOnClickAction(action:) - Set click callback</code>
///   </li>
/// </ul>
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>VideoStreamType</code>
///   </li>
///   <li>
///     <code>FillMode</code>
///   </li>
///   <li>
///     <code>RoomParticipant</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11AtomicXCore19RoomParticipantView")
@interface RoomParticipantView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class UIGestureRecognizer;

@interface RoomParticipantView (SWIFT_EXTENSION(AtomicXCore)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


@interface RoomParticipantView (SWIFT_EXTENSION(AtomicXCore))
- (void)didMoveToWindow;
- (void)layoutSubviews;
@end





SWIFT_CLASS("_TtC11AtomicXCore11SearchStore")
@interface SearchStore : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11AtomicXCore15SignalVideoView")
@interface SignalVideoView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToWindow;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


























/// View layer.
typedef SWIFT_ENUM(NSInteger, ViewLayer, open) {
/// Foreground layer.
  ViewLayerForeground = 0,
/// Background layer.
  ViewLayerBackground = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
